### PR TITLE
Enhanced dwedit functionality

### PR DESCRIPTION
**Pull request by dturkalj**
Hi,
I make this changes to old dwedit plugin downloaded from your site two years ago, and run on my local wiki, and it works very well.
When recently dw offer me an update of this plugin, I noticed that you move it to GitHub, and I decided to try to publish my changes into plugin.
Since I'm total beginner in PHP, I use code found from other plugins and make minor adjustments. 
Since you make some changes from original code, I tried to merge those changes into my modification.
Changes are:
- original view/edit icons with DW mark inside to make them visually different from original
- support edit and view mode depending on current status of page.
- show DW button only when original view/edit button is shown
- always place DW button on second place, just behind original edit/view.

I hope you will accept those changes,

best regards,
Davor

### CODE REVIEW

**Comment by turnermm** [comment]
I've made a small change in the action function which insures that the dwedit icon is hidden when dwedit mode is in effect.  I believe that is at least one thing you want to do.  So now you get the dwedit icon only when the CKEditor is in effect.  In my tests, the changes that you  made hide the dwedit icon in almost every case.
The icon you suggest using appears to be a magnifier, which  wouldn't be entirely self-evident to users.  My original intention was to alter the color of the dweit icon, and at one point it was blue but somewhere along the way that blue icon got lost.  Would you care to work on that?
Thanks.

**Comment by dturkalj** [comment]
I see, I make some test with this line of code. First I think that I can remove completely part "$ACT == 'edit' || " because there is no efect and cookie part was always active, so I need to remove it if I want to have DW Editi icons active. So for me only check to see if editor mode is dwiki. I update action.php with this.

Btw. I looked in edit.php of ckedit, and I can't see the case when $FCKG_show_preview global variable is false.

About Icons, I took original DW icons for edit (pencil) and view (magnifier), and modify them by putting letters DW to be visually different. When you have authorization to modify, pencil icon will be shown, just as original. When you don't have authorization to modify magnifier will be shown for view-only. So I follow original behavior of DW and I think that will be easy to understand for users.
Just different color will be hard to recognized, unless you use something completely different, but in that case it will ruin visual harmony of whole page. :-)

**Comment by turnermm** [comment]
Provide a name and email for the action header.

Without strict checking, `$FCKG_show_preview` resolves to as false because it is not assigned a value when first defined.

**Comment by turnermm** [comment]
This will have to be merged from the command line.  Could you provide, in addition to name and email, a revised magnifier icon, as these are not consistent:
dwedit_magn

**Comment by dturkalj** [comment]
Sorry, I lost it. Maybe we are not see the same thing, so let's elaborate.
On your picture first button is "Show pagesource" represented with magnifier (!) and it open page in ckedit in view mode.
Second button is DW View, which open DW Editor in view mode, also represented with magnifier, but with small letters DW in it, to distinguish it from first button.
Maybe here text is not consistent, "Show pagesource in DW Editor" may be better, but in my opinion only for English speakers, and it's quite long text for button. But dwedit plugin doesn't have multilanguage support yet.
In my opinion DW is universal acronym, and word View is more understandable to non-English users (like my users), and it's short.

I other case when you can edit page, you will see:
dwedit
Here pencil is used as icon representing Edit operation.
(ok, my texts are not consistent, I can easily change that) 

I'm open for any suggestion, but which icon will best describe view-only operation?
(Doku Wiki creators says it's magnifier for view and pencil for edit, and who am I to judge them :-) )

About name and email, no problem, but I didn't fill because you already have anonymous, and most part of my code is borrowed from other plugins/dw source, and doesn't seen me right to take credit for that :-)

**Comment by dturkalj** [comment]
About `$FCKG_show_preview`, I wrote that because in edit.php in function `register` (which is called first, I assume) first line define it as global, and second one set it to true. 
Other checks inside function also set it to true!
Didn't find any line in other which set's this variable to false.

I notice that because I search for code for another case which is not covered in my modif. of dwedit.
In ckedit some namespaces can be excluded from editing with ckedit, and in that case there is no need for DWedit icon ...

**Comment by turnermm** [comment]
> Maybe here text is not consistent,

I meant the magnifying glasses -- they don't appear to be the same size,  That could be be because of the different colors.  

You are right about the $FCKG_show_preview.  It is always true and it has no effect on anything.  It is a hold-over from fckgLite, which was the plugin that ckgedit replaced.  Its original function was to control when the Dokuwiki Preview Button was displayed.  You can see that in meta.php lines 261 ff.  But my commits for fckgLite on github go back only 7 years, and I  couldn't trace back how it originally was coded, but it must have been needed in fckgLite.    Perhaps you could test by commenting out meta.php lines 261-272 and all references to $FCKG_show_preview in order to see what happens.    I've tried it myself and nothing seems change.

> In ckedit some namespaces can be excluded from editing with ckedit, and in that case there is no need for DWedit icon ...

You will find the code for the excluded namespaces in edit .php lines 67ff.   You can get the excluded namespaces using that code and the following:
       ` $dwedit_ns = $this->helper->getConf('dwedit_ns'`);        
And the  cookie with 
       `$Fck_NmSp = $_COOKIE['FCK_NmSp'];`

**Comment by turnermm** [comment]
As for authorship, you certainly are an author and have spent a lot of time with it and contributed.

**Comment by dturkalj** [comment]
Ok, I recheck icons and change color of DW letters to be more compatible with rest of picture. On my first proposal color of letters is a little to dark.

Also recheck size of pencil and magnifying glass, and as I can see they are the same as original. Actually those pictures are originally taken from original DW theme, so only some resize in ccs could make the difference. What you probably notice is because when mouse is hovered over icon it change it's color to light blue, an could make it visually a little bigger.

Thanks for hints about code for namespace checking. I use it to implement blocking for excluded namespace. I check on my test DW installation, and as I can see it works.

I don't have luck with cookies. First I include code for check FCK_NmSp cookie, but funny thing happens. It hide DW Edit icon on excluded namespace, but on first visit of non-excluded page DW Edit icon is not shown! On all other pages I visit after that it is shown, including that first one, until I visit one in excluded namespace.
When I remove cookie part of code, everything starts to work correctly, so I remove this check completely.

**Comment by turnermm** [comment]
I've merged your changes into the master.  Probably you could  try to hide the dw edit icon when the dokuwiki editor is being used and the ckgeditor has been turned off.   Otherwise, it seems to work OK.  
Thanks for your work.

**Pull request merged**
